import { deflateSync } from 'node:zlib'

import { concatChunks } from '../ports/blob-store.ts'

/**
 * Images for tests: real ones, as encoders write them, and a PNG builder for
 * the tests that need a picture of a chosen size or with a chosen chunk in it.
 *
 * The fixtures below are 2×2 pictures written by Pillow 12.3 (libjpeg-turbo,
 * libpng, giflib, libwebp, libavif), each with the metadata a phone or a tool
 * leaves behind: an EXIF block with a make, a model, software, an orientation
 * and a GPS position; an XMP packet naming an author; a comment. The `plain-`
 * files are the same pixels saved with nothing else, so a test can say "this
 * is what should be left" rather than describing it. They are small enough to
 * live here as text; regenerating them is a matter of `Image.new('RGB', (2, 2))`
 * and `save(…, exif=…, xmp=…, comment=…, icc_profile=…)`.
 */
const IMAGE_FIXTURES = {
  'animated-exif.webp':
    'UklGRswBAABXRUJQVlA4WAoAAAAKAAAAAQAAAQAAQU5JTQYAAAAAAAAAAABBTk1GYAAAAAAAAAAAAAEAAAEAAGQAAAJWUDgg' +
    'SAAAAFABAJ0BKgIAAgABQCYloAAEdAAA/viHDsNBZrprn/te5RnV+ersib07Im9OyJzuaP39xPVq4nq1ab1//6gz//Vof/8t' +
    'D9bgAEFOTUZMAAAAAAAAAAAAAQAAAQAAZAAAAFZQOCA0AAAANAEAnQEqAgACAAAAJiWgAANwAP7pIh//958//7nz//ufP+jP' +
    '//8p+//yOP//I4/+UCAAAEVYSUbkAAAARXhpZgAATU0AKgAAAAgABQEPAAIAAAASAAAASgEQAAIAAAAIAAAAXAESAAMAAAAB' +
    'AAYAAAExAAIAAAAUAAAAZIglAAQAAAABAAAAeAAAAABRdWlsbCBUZXN0IENhbWVyYQBNb2RlbCBYAFF1aWxsIEZpeHR1cmUg' +
    'TWFrZXIAAAQAAQACAAAAAlMAAAAAAgAFAAAAAwAAAK4AAwACAAAAAkUAAAAABAAFAAAAAwAAAMYAAAAAAAAAJAAAAAEAAAAy' +
    'AAAAAQAAAmkAAAAyAAAArgAAAAEAAAAuAAAAAQAAAAAAAAAB',
  'animated.gif':
    'R0lGODlhAgACAIEAAMwAAMwzMzMAzAAAACH/C05FVFNDQVBFMi4wAwEAAAAh/hBhbmltYXRlZCBjb21tZW50ACH5BAAKAAAA' +
    'LAAAAAACAAIAAAgHAAMACCAgIAAh+QQBCgABACwAAAAAAgACAIEA/wAAAAAAAAAAAAAIBgABCAQQEAA7',
  'animated.png':
    'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAFHRFWHRBdXRob3IAU2VjcmV0IEF1dGhvco672vsAAAAjelRY' +
    'dENvbW1lbnQAAHicS87PLShKLS5OTVFIzs/NTc0rAQBFkgdJB9J6UgAAATRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAABlbgB4' +
    'bXAAPD94cGFja2V0IGJlZ2luPSIiIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz48eDp4bXBtZXRhIHhtbG5zOng9' +
    'ImFkb2JlOm5zOm1ldGEvIj48cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5' +
    'bnRheC1ucyMiPjxyZGY6RGVzY3JpcHRpb24gZGM6Y3JlYXRvcj0iU2VjcmV0IEF1dGhvciIgeG1sbnM6ZGM9Imh0dHA6Ly9w' +
    'dXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIi8+PC9yZGY6UkRGPjwveDp4bXBtZXRhPjw/eHBhY2tldCBlbmQ9InciPz4WpfSb' +
    'AAAACGFjVEwAAAACAAAAAPONk3AAAAAaZmNUTAAAAAAAAAACAAAAAgAAAAAAAAAAAAEACgAA6FTcAAAAABZJREFUeJxjPCEn' +
    'x8DAwMTAwBDGsAoADrACCBkl23QAAAAaZmNUTAAAAAEAAAACAAAAAgAAAAAAAAAAAAEACgAAcyc21AAAABdmZEFUAAAAAnic' +
    'Y2T4z8DAwMAEIhgYAAweAQMbVFTIAAAAAElFTkSuQmCC',
  'comment.gif':
    'R0lGODlhAgACAIEAAMwAAMwzMzMAzAAAACH+DWEgR0lGIGNvbW1lbnQALAAAAAACAAIAAAgHAAMACCAgIAA7',
  'exif.avif':
    'AAAAIGZ0eXBhdmlmAAAAAGF2aWZtaWYxbWlhZk1BMUIAAAF+bWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAA' +
    'AAAAAAAAAAAOcGl0bQAAAAAAAQAAADppbG9jAAAAAEQAAAMAAQAAAAEAAAObAAAAMAACAAAAAQAAAaYAAADcAAMAAAABAAAC' +
    'ggAAARkAAABtaWluZgAAAAAAAwAAABppbmZlAgAAAAABAABhdjAxQ29sb3IAAAAAGWluZmUCAAAAAAIAAEV4aWZFeGlmAAAA' +
    'ACxpbmZlAgAAAAADAABtaW1lWE1QAGFwcGxpY2F0aW9uL3JkZit4bWwAAAAAKGlyZWYAAAAAAAAADmNkc2MAAgABAAEAAAAO' +
    'Y2RzYwADAAEAAQAAAHRpcHJwAAAAVGlwY28AAAAUaXNwZQAAAAAAAAACAAAAAgAAABBwaXhpAAAAAAMICAgAAAAMYXYxQ4EA' +
    'DAAAAAATY29scm5jbHgAAQANAAaAAAAACWlyb3QDAAAAGGlwbWEAAAAAAAAAAQABBQECgwSFAAACLW1kYXQAAAAGRXhpZgAA' +
    'TU0AKgAAAAgABAEPAAIAAAASAAAAPgEQAAIAAAAIAAAAUAExAAIAAAAUAAAAWIglAAQAAAABAAAAbAAAAABRdWlsbCBUZXN0' +
    'IENhbWVyYQBNb2RlbCBYAFF1aWxsIEZpeHR1cmUgTWFrZXIAAAQAAQACAAAAAlMAAAAAAgAFAAAAAwAAAKIAAwACAAAAAkUA' +
    'AAAABAAFAAAAAwAAALoAAAAAAAAAJAAAAAEAAAAyAAAAAQAAAmkAAAAyAAAArgAAAAEAAAAuAAAAAQAAAAAAAAABPD94cGFj' +
    'a2V0IGJlZ2luPSIiIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz48eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5z' +
    'Om1ldGEvIj48cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMi' +
    'PjxyZGY6RGVzY3JpcHRpb24gZGM6Y3JlYXRvcj0iU2VjcmV0IEF1dGhvciIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9k' +
    'Yy9lbGVtZW50cy8xLjEvIi8+PC9yZGY6UkRGPjwveDp4bXBtZXRhPjw/eHBhY2tldCBlbmQ9InciPz4SAAoIGAA2iAhoNCAy' +
    'IhPHh4ZlAYYYfhAAAAD2byth4IHdWwhBSsscuvwdgAd1kWw=',
  'exif.jpg':
    '/9j/4AAQSkZJRgABAQAAAQABAAD/4QDmRXhpZgAATU0AKgAAAAgABQEPAAIAAAASAAAASgEQAAIAAAAIAAAAXAESAAMAAAAB' +
    'AAYAAAExAAIAAAAUAAAAZIglAAQAAAABAAAAeAAAAABRdWlsbCBUZXN0IENhbWVyYQBNb2RlbCBYAFF1aWxsIEZpeHR1cmUg' +
    'TWFrZXIAAAQAAQACAAAAAlMAAAAAAgAFAAAAAwAAAK4AAwACAAAAAkUAAAAABAAFAAAAAwAAAMYAAAAAAAAAJAAAAAEAAAAy' +
    'AAAAAQAAAmkAAAAyAAAArgAAAAEAAAAuAAAAAQAAAAAAAAAB/+EBOGh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8APD94' +
    'cGFja2V0IGJlZ2luPSIiIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz48eDp4bXBtZXRhIHhtbG5zOng9ImFkb2Jl' +
    'Om5zOm1ldGEvIj48cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1u' +
    'cyMiPjxyZGY6RGVzY3JpcHRpb24gZGM6Y3JlYXRvcj0iU2VjcmV0IEF1dGhvciIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9y' +
    'Zy9kYy9lbGVtZW50cy8xLjEvIi8+PC9yZGY6UkRGPjwveDp4bXBtZXRhPjw/eHBhY2tldCBlbmQ9InciPz7//gAQYSBKUEVH' +
    'IGNvbW1lbnT/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0o' +
    'MCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo' +
    'KCj/wAARCAACAAIDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA' +
    'AAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVW' +
    'V1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ' +
    '2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQA' +
    'AQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RV' +
    'VldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX' +
    '2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDyC6uJluZgJZAA5AAY+tFFFe5R/hx9EfWVfjl6n//Z',
  'exif.webp':
    'UklGRkACAABXRUJQVlA4WAoAAAAMAAAAAQAAAQAAVlA4TBkAAAAvAUAAAA8wHvdQvRXy/EcLFAIIgIImov+xAEVYSUbeAAAA' +
    'TU0AKgAAAAgABQEPAAIAAAASAAAASgEQAAIAAAAIAAAAXAESAAMAAAABAAYAAAExAAIAAAAUAAAAZIglAAQAAAABAAAAeAAA' +
    'AABRdWlsbCBUZXN0IENhbWVyYQBNb2RlbCBYAFF1aWxsIEZpeHR1cmUgTWFrZXIAAAQAAQACAAAAAlMAAAAAAgAFAAAAAwAA' +
    'AK4AAwACAAAAAkUAAAAABAAFAAAAAwAAAMYAAAAAAAAAJAAAAAEAAAAyAAAAAQAAAmkAAAAyAAAArgAAAAEAAAAuAAAAAQAA' +
    'AAAAAAABWE1QIBkBAAA8P3hwYWNrZXQgYmVnaW49IiIgaWQ9Ilc1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCI/Pjx4OnhtcG1l' +
    'dGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iPjxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8w' +
    'Mi8yMi1yZGYtc3ludGF4LW5zIyI+PHJkZjpEZXNjcmlwdGlvbiBkYzpjcmVhdG9yPSJTZWNyZXQgQXV0aG9yIiB4bWxuczpk' +
    'Yz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iLz48L3JkZjpSREY+PC94OnhtcG1ldGE+PD94cGFja2V0IGVu' +
    'ZD0idyI/PgA=',
  'icc-exif.jpg':
    '/9j/4AAQSkZJRgABAQAAAQABAAD/4QDmRXhpZgAATU0AKgAAAAgABQEPAAIAAAASAAAASgEQAAIAAAAIAAAAXAESAAMAAAAB' +
    'AAYAAAExAAIAAAAUAAAAZIglAAQAAAABAAAAeAAAAABRdWlsbCBUZXN0IENhbWVyYQBNb2RlbCBYAFF1aWxsIEZpeHR1cmUg' +
    'TWFrZXIAAAQAAQACAAAAAlMAAAAAAgAFAAAAAwAAAK4AAwACAAAAAkUAAAAABAAFAAAAAwAAAMYAAAAAAAAAJAAAAAEAAAAy' +
    'AAAAAQAAAmkAAAAyAAAArgAAAAEAAAAuAAAAAQAAAAAAAAAB/+ICXElDQ19QUk9GSUxFAAEBAAACTGxjbXMEQAAAbW50clJH' +
    'QiBYWVogB+oACQANAAQABwA4YWNzcE1TRlQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1sY21zAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALZGVzYwAAAQgAAAA2Y3BydAAAAUAAAABMd3RwdAAA' +
    'AYwAAAAUY2hhZAAAAaAAAAAsclhZWgAAAcwAAAAUYlhZWgAAAeAAAAAUZ1hZWgAAAfQAAAAUclRSQwAAAggAAAAgZ1RSQwAA' +
    'AggAAAAgYlRSQwAAAggAAAAgY2hybQAAAigAAAAkbWx1YwAAAAAAAAABAAAADGVuVVMAAAAaAAAAHABzAFIARwBCACAAYgB1' +
    'AGkAbAB0AC0AaQBuAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAADAAAAAcAE4AbwAgAGMAbwBwAHkAcgBpAGcAaAB0ACwAIAB1' +
    'AHMAZQAgAGYAcgBlAGUAbAB5WFlaIAAAAAAAAPbWAAEAAAAA0y1zZjMyAAAAAAABDEIAAAXe///zJQAAB5MAAP2Q///7of//' +
    '/aIAAAPcAADAblhZWiAAAAAAAABvoAAAOPUAAAOQWFlaIAAAAAAAACSfAAAPhAAAtsNYWVogAAAAAAAAYpcAALeHAAAY2XBh' +
    'cmEAAAAAAAMAAAACZmYAAPKnAAANWQAAE9AAAApbY2hybQAAAAAAAwAAAACj1wAAVHsAAEzNAACZmgAAJmYAAA9c/9sAQwAG' +
    'BAUGBQQGBgUGBwcGCAoQCgoJCQoUDg8MEBcUGBgXFBYWGh0lHxobIxwWFiAsICMmJykqKRkfLTAtKDAlKCko/9sAQwEHBwcK' +
    'CAoTCgoTKBoWGigoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo/8AAEQgAAgACAwEi' +
    'AAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFB' +
    'BhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0' +
    'dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz' +
    '9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYS' +
    'QVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpz' +
    'dHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz' +
    '9PX29/j5+v/aAAwDAQACEQMRAD8A8guriZbmYCWQAOQAGPrRRRXuUf4cfRH1lX45ep//2Q==',
  'icc-exif.webp':
    'UklGRnIDAABXRUJQVlA4WAoAAAAoAAAAAQAAAQAASUNDUEwCAAAAAAJMbGNtcwRAAABtbnRyUkdCIFhZWiAH6gAJAA0ABAAH' +
    'ADhhY3NwTVNGVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWxjbXMAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtkZXNjAAABCAAAADZjcHJ0AAABQAAAAEx3dHB0AAABjAAAABRjaGFkAAABoAAA' +
    'ACxyWFlaAAABzAAAABRiWFlaAAAB4AAAABRnWFlaAAAB9AAAABRyVFJDAAACCAAAACBnVFJDAAACCAAAACBiVFJDAAACCAAA' +
    'ACBjaHJtAAACKAAAACRtbHVjAAAAAAAAAAEAAAAMZW5VUwAAABoAAAAcAHMAUgBHAEIAIABiAHUAaQBsAHQALQBpAG4AAG1s' +
    'dWMAAAAAAAAAAQAAAAxlblVTAAAAMAAAABwATgBvACAAYwBvAHAAeQByAGkAZwBoAHQALAAgAHUAcwBlACAAZgByAGUAZQBs' +
    'AHlYWVogAAAAAAAA9tYAAQAAAADTLXNmMzIAAAAAAAEMQgAABd7///MlAAAHkwAA/ZD///uh///9ogAAA9wAAMBuWFlaIAAA' +
    'AAAAAG+gAAA49QAAA5BYWVogAAAAAAAAJJ8AAA+EAAC2w1hZWiAAAAAAAABilwAAt4cAABjZcGFyYQAAAAAAAwAAAAJmZgAA' +
    '8qcAAA1ZAAAT0AAACltjaHJtAAAAAAADAAAAAKPXAABUewAATM0AAJmaAAAmZgAAD1xWUDhMGQAAAC8BQAAADzAe91C9FfL8' +
    'RwsUAgiAgiai/7EARVhJRt4AAABNTQAqAAAACAAFAQ8AAgAAABIAAABKARAAAgAAAAgAAABcARIAAwAAAAEABgAAATEAAgAA' +
    'ABQAAABkiCUABAAAAAEAAAB4AAAAAFF1aWxsIFRlc3QgQ2FtZXJhAE1vZGVsIFgAUXVpbGwgRml4dHVyZSBNYWtlcgAABAAB' +
    'AAIAAAACUwAAAAACAAUAAAADAAAArgADAAIAAAACRQAAAAAEAAUAAAADAAAAxgAAAAAAAAAkAAAAAQAAADIAAAABAAACaQAA' +
    'ADIAAACuAAAAAQAAAC4AAAABAAAAAAAAAAE=',
  'meta.png':
    'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAFHRFWHRBdXRob3IAU2VjcmV0IEF1dGhvco672vsAAAAjelRY' +
    'dENvbW1lbnQAAHicS87PLShKLS5OTVFIzs/NTc0rAQBFkgdJB9J6UgAAATRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAABlbgB4' +
    'bXAAPD94cGFja2V0IGJlZ2luPSIiIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz48eDp4bXBtZXRhIHhtbG5zOng9' +
    'ImFkb2JlOm5zOm1ldGEvIj48cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5' +
    'bnRheC1ucyMiPjxyZGY6RGVzY3JpcHRpb24gZGM6Y3JlYXRvcj0iU2VjcmV0IEF1dGhvciIgeG1sbnM6ZGM9Imh0dHA6Ly9w' +
    'dXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIi8+PC9yZGY6UkRGPjwveDp4bXBtZXRhPjw/eHBhY2tldCBlbmQ9InciPz4WpfSb' +
    'AAAA3mVYSWZNTQAqAAAACAAFAQ8AAgAAABIAAABKARAAAgAAAAgAAABcARIAAwAAAAEABgAAATEAAgAAABQAAABkiCUABAAA' +
    'AAEAAAB4AAAAAFF1aWxsIFRlc3QgQ2FtZXJhAE1vZGVsIFgAUXVpbGwgRml4dHVyZSBNYWtlcgAABAABAAIAAAACUwAAAAAC' +
    'AAUAAAADAAAArgADAAIAAAACRQAAAAAEAAUAAAADAAAAxgAAAAAAAAAkAAAAAQAAADIAAAABAAACaQAAADIAAACuAAAAAQAA' +
    'AC4AAAABAAAAAAAAAAF5k3xwAAAAFklEQVR4nGM8ISfHwMDAxMDAEMawCgAOsAIIGSXbdAAAAABJRU5ErkJggg==',
  'plain.avif':
    'AAAAIGZ0eXBhdmlmAAAAAGF2aWZtaWYxbWlhZk1BMUIAAADrbWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAA' +
    'AAAAAAAAAAAOcGl0bQAAAAAAAQAAAB5pbG9jAAAAAEQAAAEAAQAAAAEAAAETAAAAMAAAAChpaW5mAAAAAAABAAAAGmluZmUC' +
    'AAAAAAEAAGF2MDFDb2xvcgAAAABqaXBycAAAAEtpcGNvAAAAFGlzcGUAAAAAAAAAAgAAAAIAAAAQcGl4aQAAAAADCAgIAAAA' +
    'DGF2MUOBAAwAAAAAE2NvbHJuY2x4AAEADQAGgAAAABdpcG1hAAAAAAAAAAEAAQQBAoMEAAAAOG1kYXQSAAoIGAA2iAhoNCAy' +
    'IhPHh4ZlAYYYfhAAAAD2byth4IHdWwhBSsscuvwdgAd1kWw=',
  'plain.gif': 'R0lGODdhAgACAIEAAMwAAMwzMzMAzAAAACwAAAAAAgACAAAIBwADAAggICAAOw==',
  'plain.jpg':
    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwg' +
    'IyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo' +
    'KCgoKCgoKCgoKCgoKCj/wAARCAACAAIDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAA' +
    'AgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6' +
    'Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXG' +
    'x8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREA' +
    'AgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5' +
    'OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPE' +
    'xcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDyC6uJluZgJZAA5AAY+tFFFe5R/hx9EfWV' +
    'fjl6n//Z',
  'plain.png':
    'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAFklEQVR4nGM8ISfHwMDAxMDAEMawCgAOsAIIGSXbdAAAAABJ' +
    'RU5ErkJggg==',
  'plain.webp':
    'UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoCAAIAAUAmJaACdAEO9p5AAP76l6noG+hcHaZ/h/9QZ//q0P/+Wh+twAA=',
  'progressive-exif.jpg':
    '/9j/4AAQSkZJRgABAQAAAQABAAD/4QDmRXhpZgAATU0AKgAAAAgABQEPAAIAAAASAAAASgEQAAIAAAAIAAAAXAESAAMAAAAB' +
    'AAYAAAExAAIAAAAUAAAAZIglAAQAAAABAAAAeAAAAABRdWlsbCBUZXN0IENhbWVyYQBNb2RlbCBYAFF1aWxsIEZpeHR1cmUg' +
    'TWFrZXIAAAQAAQACAAAAAlMAAAAAAgAFAAAAAwAAAK4AAwACAAAAAkUAAAAABAAFAAAAAwAAAMYAAAAAAAAAJAAAAAEAAAAy' +
    'AAAAAQAAAmkAAAAyAAAArgAAAAEAAAAuAAAAAQAAAAAAAAAB/9sAQwAGBAUGBQQGBgUGBwcGCAoQCgoJCQoUDg8MEBcUGBgX' +
    'FBYWGh0lHxobIxwWFiAsICMmJykqKRkfLTAtKDAlKCko/9sAQwEHBwcKCAoTCgoTKBoWGigoKCgoKCgoKCgoKCgoKCgoKCgo' +
    'KCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgo/8IAEQgAAgACAwEiAAIRAQMRAf/EABUAAQEAAAAAAAAAAAAAAAAAAAAG' +
    '/8QAFQEBAQAAAAAAAAAAAAAAAAAABAX/2gAMAwEAAhADEAAAAY8Orf/EABYQAQEBAAAAAAAAAAAAAAAAAAIBEv/aAAgBAQAB' +
    'BQJK6//EABcRAAMBAAAAAAAAAAAAAAAAAAABAjH/2gAIAQMBAT8BrWf/xAAXEQADAQAAAAAAAAAAAAAAAAAAAQIy/9oACAEC' +
    'AQE/AYyj/8QAFhABAQEAAAAAAAAAAAAAAAAAAQAh/9oACAEBAAY/AnW//8QAFhABAQEAAAAAAAAAAAAAAAAAUQAB/9oACAEB' +
    'AAE/Icqjf//aAAwDAQACAAMAAAAQ8//EABURAQEAAAAAAAAAAAAAAAAAAACh/9oACAEDAQE/ELn/xAAWEQADAAAAAAAAAAAA' +
    'AAAAAAAAAaH/2gAIAQIBAT8QgR//xAAWEAEBAQAAAAAAAAAAAAAAAAABAFH/2gAIAQEAAT8QAggYAtv/2Q==',
} as const

export type ImageFixtureName = keyof typeof IMAGE_FIXTURES

export function imageFixture(name: ImageFixtureName): Uint8Array {
  return Uint8Array.from(Buffer.from(IMAGE_FIXTURES[name], 'base64'))
}

/** The body as the platform receives it: a stream of chunks, not a buffer. */
export async function* chunked(bytes: Uint8Array, chunkSize = 8): AsyncGenerator<Uint8Array> {
  for (let offset = 0; offset < bytes.length; offset += chunkSize) {
    yield bytes.subarray(offset, Math.min(offset + chunkSize, bytes.length))
  }
}

export const PNG_SIGNATURE = Uint8Array.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])

export interface PngFileOptions {
  readonly width?: number
  readonly height?: number
  /** Chunks placed between `IHDR` and `IDAT`, already framed by `pngChunk`. */
  readonly chunks?: readonly Uint8Array[]
}

/**
 * A complete, decodable RGB PNG of the given size.
 *
 * The pixels are stored rather than compressed, so the file grows with its
 * area: a test that needs a picture longer than a buffer asks for a bigger one.
 */
export function pngFile({ width = 1, height = 1, chunks = [] }: PngFileOptions = {}): Uint8Array {
  const header = new Uint8Array(13)
  const view = new DataView(header.buffer)
  view.setUint32(0, width)
  view.setUint32(4, height)
  header[8] = 8 // bit depth
  header[9] = 2 // colour type: RGB
  const rows = new Uint8Array(height * (1 + width * 3))
  for (let y = 0; y < height; y += 1) {
    const row = y * (1 + width * 3)
    for (let x = 0; x < width; x += 1) {
      const pixel = row + 1 + x * 3
      rows[pixel] = (x * 37 + y * 11) & 0xff
      rows[pixel + 1] = (x * 5 + y * 29) & 0xff
      rows[pixel + 2] = (x ^ y) & 0xff
    }
  }
  const stored = new Uint8Array(deflateSync(rows, { level: 0 }))
  return concatChunks([
    PNG_SIGNATURE,
    pngChunk('IHDR', header),
    ...chunks,
    pngChunk('IDAT', stored),
    pngChunk('IEND', new Uint8Array()),
  ])
}

/** A PNG chunk as the file carries it: length, type, data, and a correct CRC. */
export function pngChunk(type: string, data: Uint8Array): Uint8Array {
  const chunk = new Uint8Array(12 + data.length)
  const view = new DataView(chunk.buffer)
  view.setUint32(0, data.length)
  chunk.set(new TextEncoder().encode(type), 4)
  chunk.set(data, 8)
  view.setUint32(8 + data.length, crc32(chunk.subarray(4, 8 + data.length)))
  return chunk
}

const CRC_TABLE = Uint32Array.from({ length: 256 }, (_, n) => {
  let c = n
  for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
  return c >>> 0
})

function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff
  for (const byte of bytes) crc = (CRC_TABLE[(crc ^ byte) & 0xff] as number) ^ (crc >>> 8)
  return (crc ^ 0xffffffff) >>> 0
}
