/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as DesignRouteImport } from './routes/design'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAdminOrganisationRouteImport } from './routes/_authenticated/admin/organisation'
import { Route as AuthenticatedWWorkspaceSlugRouteRouteImport } from './routes/_authenticated/w/$workspaceSlug/route'
import { Route as AuthenticatedWWorkspaceSlugIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/index'
import { Route as AuthenticatedWWorkspaceSlugDDocumentIdIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/d/$documentId/index'
import { Route as AuthenticatedWWorkspaceSlugDDocumentIdEditRouteImport } from './routes/_authenticated/w/$workspaceSlug/d/$documentId/edit'
import { Route as AuthenticatedWWorkspaceSlugDDocumentIdPresentRouteImport } from './routes/_authenticated/w/$workspaceSlug_/d/$documentId/present'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminOrganisationRoute =
  AuthenticatedAdminOrganisationRouteImport.update({
    id: '/admin/organisation',
    path: '/admin/organisation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugRouteRoute =
  AuthenticatedWWorkspaceSlugRouteRouteImport.update({
    id: '/w/$workspaceSlug',
    path: '/w/$workspaceSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugIndexRoute =
  AuthenticatedWWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugDDocumentIdIndexRoute =
  AuthenticatedWWorkspaceSlugDDocumentIdIndexRouteImport.update({
    id: '/d/$documentId/',
    path: '/d/$documentId/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugDDocumentIdEditRoute =
  AuthenticatedWWorkspaceSlugDDocumentIdEditRouteImport.update({
    id: '/d/$documentId/edit',
    path: '/d/$documentId/edit',
    getParentRoute: () => AuthenticatedWWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugDDocumentIdPresentRoute =
  AuthenticatedWWorkspaceSlugDDocumentIdPresentRouteImport.update({
    id: '/w/$workspaceSlug_/d/$documentId/present',
    path: '/w/$workspaceSlug/d/$documentId/present',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/magic-link': typeof MagicLinkRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/w/$workspaceSlug': typeof AuthenticatedWWorkspaceSlugRouteRouteWithChildren
  '/admin/organisation': typeof AuthenticatedAdminOrganisationRoute
  '/w/$workspaceSlug/': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/w/$workspaceSlug/d/$documentId/edit': typeof AuthenticatedWWorkspaceSlugDDocumentIdEditRoute
  '/w/$workspaceSlug/d/$documentId/present': typeof AuthenticatedWWorkspaceSlugDDocumentIdPresentRoute
  '/w/$workspaceSlug/d/$documentId/': typeof AuthenticatedWWorkspaceSlugDDocumentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/magic-link': typeof MagicLinkRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/organisation': typeof AuthenticatedAdminOrganisationRoute
  '/w/$workspaceSlug': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/w/$workspaceSlug/d/$documentId/edit': typeof AuthenticatedWWorkspaceSlugDDocumentIdEditRoute
  '/w/$workspaceSlug/d/$documentId/present': typeof AuthenticatedWWorkspaceSlugDDocumentIdPresentRoute
  '/w/$workspaceSlug/d/$documentId': typeof AuthenticatedWWorkspaceSlugDDocumentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/design': typeof DesignRoute
  '/magic-link': typeof MagicLinkRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/w/$workspaceSlug': typeof AuthenticatedWWorkspaceSlugRouteRouteWithChildren
  '/_authenticated/admin/organisation': typeof AuthenticatedAdminOrganisationRoute
  '/_authenticated/w/$workspaceSlug/': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/_authenticated/w/$workspaceSlug/d/$documentId/edit': typeof AuthenticatedWWorkspaceSlugDDocumentIdEditRoute
  '/_authenticated/w/$workspaceSlug_/d/$documentId/present': typeof AuthenticatedWWorkspaceSlugDDocumentIdPresentRoute
  '/_authenticated/w/$workspaceSlug/d/$documentId/': typeof AuthenticatedWWorkspaceSlugDDocumentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/magic-link'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/w/$workspaceSlug'
    | '/admin/organisation'
    | '/w/$workspaceSlug/'
    | '/w/$workspaceSlug/d/$documentId/edit'
    | '/w/$workspaceSlug/d/$documentId/present'
    | '/w/$workspaceSlug/d/$documentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/magic-link'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/admin/organisation'
    | '/w/$workspaceSlug'
    | '/w/$workspaceSlug/d/$documentId/edit'
    | '/w/$workspaceSlug/d/$documentId/present'
    | '/w/$workspaceSlug/d/$documentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/design'
    | '/magic-link'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/_authenticated/w/$workspaceSlug'
    | '/_authenticated/admin/organisation'
    | '/_authenticated/w/$workspaceSlug/'
    | '/_authenticated/w/$workspaceSlug/d/$documentId/edit'
    | '/_authenticated/w/$workspaceSlug_/d/$documentId/present'
    | '/_authenticated/w/$workspaceSlug/d/$documentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DesignRoute: typeof DesignRoute
  MagicLinkRoute: typeof MagicLinkRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/organisation': {
      id: '/_authenticated/admin/organisation'
      path: '/admin/organisation'
      fullPath: '/admin/organisation'
      preLoaderRoute: typeof AuthenticatedAdminOrganisationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/w/$workspaceSlug': {
      id: '/_authenticated/w/$workspaceSlug'
      path: '/w/$workspaceSlug'
      fullPath: '/w/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/': {
      id: '/_authenticated/w/$workspaceSlug/'
      path: '/'
      fullPath: '/w/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/d/$documentId/': {
      id: '/_authenticated/w/$workspaceSlug/d/$documentId/'
      path: '/d/$documentId'
      fullPath: '/w/$workspaceSlug/d/$documentId/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugDDocumentIdIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/d/$documentId/edit': {
      id: '/_authenticated/w/$workspaceSlug/d/$documentId/edit'
      path: '/d/$documentId/edit'
      fullPath: '/w/$workspaceSlug/d/$documentId/edit'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugDDocumentIdEditRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugRouteRoute
    }
    '/_authenticated/w/$workspaceSlug_/d/$documentId/present': {
      id: '/_authenticated/w/$workspaceSlug_/d/$documentId/present'
      path: '/w/$workspaceSlug/d/$documentId/present'
      fullPath: '/w/$workspaceSlug/d/$documentId/present'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugDDocumentIdPresentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedWWorkspaceSlugRouteRouteChildren {
  AuthenticatedWWorkspaceSlugIndexRoute: typeof AuthenticatedWWorkspaceSlugIndexRoute
  AuthenticatedWWorkspaceSlugDDocumentIdEditRoute: typeof AuthenticatedWWorkspaceSlugDDocumentIdEditRoute
  AuthenticatedWWorkspaceSlugDDocumentIdIndexRoute: typeof AuthenticatedWWorkspaceSlugDDocumentIdIndexRoute
}

const AuthenticatedWWorkspaceSlugRouteRouteChildren: AuthenticatedWWorkspaceSlugRouteRouteChildren =
  {
    AuthenticatedWWorkspaceSlugIndexRoute:
      AuthenticatedWWorkspaceSlugIndexRoute,
    AuthenticatedWWorkspaceSlugDDocumentIdEditRoute:
      AuthenticatedWWorkspaceSlugDDocumentIdEditRoute,
    AuthenticatedWWorkspaceSlugDDocumentIdIndexRoute:
      AuthenticatedWWorkspaceSlugDDocumentIdIndexRoute,
  }

const AuthenticatedWWorkspaceSlugRouteRouteWithChildren =
  AuthenticatedWWorkspaceSlugRouteRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWWorkspaceSlugRouteRoute: typeof AuthenticatedWWorkspaceSlugRouteRouteWithChildren
  AuthenticatedAdminOrganisationRoute: typeof AuthenticatedAdminOrganisationRoute
  AuthenticatedWWorkspaceSlugDDocumentIdPresentRoute: typeof AuthenticatedWWorkspaceSlugDDocumentIdPresentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWWorkspaceSlugRouteRoute:
    AuthenticatedWWorkspaceSlugRouteRouteWithChildren,
  AuthenticatedAdminOrganisationRoute: AuthenticatedAdminOrganisationRoute,
  AuthenticatedWWorkspaceSlugDDocumentIdPresentRoute:
    AuthenticatedWWorkspaceSlugDDocumentIdPresentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DesignRoute: DesignRoute,
  MagicLinkRoute: MagicLinkRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
