import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

import {
  grammarTokenGroups,
  REVIEWED_UNTHEMED_GROUPS,
  resolveTokenClass,
  SUPPORTED_LANGUAGES,
  tokenCssContract,
  tokenGroupKey,
  type TokenClass,
  unthemedTokenGroups,
} from '@quill/highlight'
import { BUILTIN_THEME_IDS, DEFAULT_THEME } from '@quill/theme'

import { THEME_ID_ATTRIBUTE } from '../theme/theme-id.ts'
import {
  generatedStylesheets,
  REGENERATE_COMMAND,
  syntaxStylesheet,
  themeScope,
} from './generated-css.ts'

const read = (path: string): string =>
  readFileSync(fileURLToPath(new URL(path, import.meta.url)), 'utf8')

const declares = (css: string, name: string): boolean => new RegExp(`^\\s*${name}:`, 'm').test(css)

const selectorsOf = (css: string): readonly string[] =>
  [...css.matchAll(/^(\S[^\n{]*) \{$/gm)].map(([, selector]) => selector ?? '')

const escapeForRegExp = (raw: string): string => raw.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

/**
 * The declarations inside one selector's block, given the exact selector
 * text `toCss` emits it with. Matches on the selector's own indentation so
 * the dark media query's nested block isn't confused with the ones at the
 * top level.
 */
const blockFor = (css: string, selector: string): string => {
  const pattern = new RegExp(
    `^([ \\t]*)${escapeForRegExp(selector)} \\{\\n([\\s\\S]*?)\\n\\1\\}$`,
    'm',
  )
  const match = pattern.exec(css)
  if (match === null) throw new Error(`no "${selector}" block found`)
  return match[2] ?? ''
}

/**
 * The selectors that carry a theme's actual custom properties for the light
 * scheme and for the dark scheme (media-query and explicit-attribute both) —
 * everything but the explicit `[data-theme='light']` block, which `toCss`
 * leaves empty because it only overrides `color-scheme` back to light.
 */
const schemeSelectors = (scope: string): readonly string[] => [
  scope,
  `${scope}:not([data-theme='light'])`,
  `${scope}[data-theme='dark']`,
]

describe('the generated stylesheets', () => {
  it.each(generatedStylesheets())('has $path on disk exactly as generated', ({ path, css }) => {
    expect(read(`./${path}`), `src/styles/${path} is stale. Run \`${REGENERATE_COMMAND}\`.`).toBe(
      css,
    )
  })

  it.each(generatedStylesheets())('names the command that regenerates $path', ({ path }) => {
    const [firstLine] = read(`./${path}`).split('\n')
    expect(firstLine).toBe(`/* Generated by \`${REGENERATE_COMMAND}\`. Do not edit. */`)
  })

  it('scopes the default theme to the absent attribute as well as its own id', () => {
    expect(DEFAULT_THEME.id).toBe('instrument')
    expect(themeScope('instrument')).toBe(
      `:root:where(:not([${THEME_ID_ATTRIBUTE}]), [${THEME_ID_ATTRIBUTE}='instrument'])`,
    )
  })

  it.each(['press', 'atelier'] as const)('scopes %s to its own id alone', (id) => {
    expect(themeScope(id)).toBe(`:root[${THEME_ID_ATTRIBUTE}='${id}']`)
  })

  it.each(BUILTIN_THEME_IDS)(
    'covers light, the dark media block, and the explicit dark attribute for %s',
    (id) => {
      const css = read(`./generated/${id}.gen.css`)
      const scope = themeScope(id)

      expect(css).toContain(`${scope} {`)
      expect(css).toContain(`${scope}:not([data-theme='light']) {`)
      expect(css).toContain(`${scope}[data-theme='dark'] {`)
      expect(css).toContain(`${scope}[data-theme='light'] {`)

      // The media block resolves before the explicit attributes, which is what
      // makes "follow the system" the absence of `data-theme`.
      expect(css.indexOf('@media (prefers-color-scheme: dark)')).toBeLessThan(
        css.indexOf(`${scope}[data-theme='dark']`),
      )
    },
  )
})

describe('the semantic layer and the generated palettes', () => {
  const referenced = [
    ...new Set(
      [...read('./tokens.css').matchAll(/var\((--palette-[a-z-]+)\)/g)].map(
        ([, name]) => name ?? '',
      ),
    ),
  ]

  it('references at least the surfaces, the ink, the accent, and the status colours', () => {
    expect(referenced.length).toBeGreaterThanOrEqual(20)
  })

  it.each(BUILTIN_THEME_IDS)('emits every referenced palette name in %s', (id) => {
    const css = read(`./generated/${id}.gen.css`)
    expect(referenced.filter((name) => !declares(css, name))).toEqual([])
  })
})

describe('the syntax token stylesheet', () => {
  const css = syntaxStylesheet()
  const { variables, classSelectors, highlightSelectors } = tokenCssContract()

  it('states each rule separately, so a browser without ::highlight() keeps the class rules', () => {
    expect(selectorsOf(css).filter((selector) => selector.includes(','))).toEqual([])

    for (const [index, variable] of variables.entries()) {
      expect(css).toContain(`${classSelectors[index]} {\n  color: var(${variable});\n}`)
      expect(css).toContain(`${highlightSelectors[index]} {\n  color: var(${variable});\n}`)
    }
  })

  it.each(SUPPORTED_LANGUAGES)(
    'leaves exactly the reviewed groups of %s uncoloured',
    (language) => {
      // Mirrors packages/highlight's own assertion, against the same
      // allowlist: a grammar upgrade that starts emitting an unreviewed,
      // uncoloured class fails here rather than rendering it unthemed.
      expect(unthemedTokenGroups(language)).toEqual(
        [...new Set(REVIEWED_UNTHEMED_GROUPS[language])].toSorted(),
      )
    },
  )

  it.each(SUPPORTED_LANGUAGES)(
    'colours every non-reviewed class the %s grammar can emit, in every theme and scheme',
    (language) => {
      const reviewed = new Set(REVIEWED_UNTHEMED_GROUPS[language])
      const resolved = grammarTokenGroups(language)
        .filter((group) => !reviewed.has(tokenGroupKey(group)))
        .map((group) => resolveTokenClass(group))

      // Loud by construction: a group left out of the allowlist above but
      // still unresolved here would otherwise vanish silently on the next
      // filter, which was the original defect.
      expect(resolved).not.toContain(null)
      const classes = new Set(resolved as TokenClass[])
      expect(classes.size).toBeGreaterThan(0)

      for (const tokenClass of classes) {
        expect(css).toContain(`.tok-${tokenClass} {`)
        expect(css).toContain(`::highlight(quill-tok-${tokenClass}) {`)
        for (const id of BUILTIN_THEME_IDS) {
          const themeCss = read(`./generated/${id}.gen.css`)
          const scope = themeScope(id)
          for (const selector of schemeSelectors(scope)) {
            expect(
              declares(blockFor(themeCss, selector), `--token-${tokenClass}`),
              `${id}.gen.css is missing --token-${tokenClass} in "${selector}"`,
            ).toBe(true)
          }
        }
      }
    },
  )
})
