/**
 * The stylesheets that are generated rather than written.
 *
 * ADR-028 makes generation the only source of colour: a theme document
 * resolves to two token maps, and those token maps become CSS. ADR-030 makes
 * `packages/highlight` the only source of syntax token classes. Neither list
 * is retyped here — this module is the small amount of arrangement between
 * them and the files on disk, and `generate-tokens.ts` is the only thing that
 * writes it out.
 *
 * Keeping the arrangement in `src` rather than in the script is what lets
 * `generated-css.test.ts` regenerate and compare, so a stale file on disk
 * fails the build instead of quietly shipping last week's palette. The output
 * carries the `.gen.css` suffix, which is what excludes it from the formatter
 * and the coverage report — that test is the only thing keeping it honest.
 */
import { tokenCssContract } from '@quill/highlight'
import {
  BUILTIN_THEMES,
  BUILTIN_THEME_IDS,
  generateTheme,
  toCss,
  type BuiltinThemeId,
} from '@quill/theme'

import { DEFAULT_THEME_ID, THEME_ID_ATTRIBUTE } from '../theme/theme-id.ts'

export interface GeneratedStylesheet {
  /** Path relative to `packages/ui/src/styles`, in POSIX form, ending `.gen.css`. */
  readonly path: string
  readonly css: string
}

/**
 * The scope a theme's custom properties apply in.
 *
 * A `:where()` keeps the default theme at the specificity of a bare `:root`
 * while still matching its own id, and the two arms are mutually exclusive,
 * so exactly one theme's block ever applies. `toCss` appends the colour
 * scheme selectors to whatever it is given, which is why this has to stay a
 * single compound selector rather than a selector list.
 */
export const themeScope = (id: BuiltinThemeId): string =>
  id === DEFAULT_THEME_ID
    ? `:root:where(:not([${THEME_ID_ATTRIBUTE}]), [${THEME_ID_ATTRIBUTE}='${id}'])`
    : `:root[${THEME_ID_ATTRIBUTE}='${id}']`

/** Named once, so the first line of every generated file can say it. */
export const REGENERATE_COMMAND = 'pnpm --filter @quill/ui generate:tokens'

const banner = (source: string): string =>
  [
    `/* Generated by \`${REGENERATE_COMMAND}\`. Do not edit. */`,
    '/*',
    ` * Written from ${source}.`,
    ' *',
    ' * `generated-css.test.ts` regenerates and compares, so an edit here is a',
    ' * failing test rather than a drift. The `.gen.css` suffix is what keeps',
    ' * the formatter and the coverage report out of it.',
    ' */',
    '',
    '',
  ].join('\n')

/** One built-in identity's palettes, in the resolution order of `tokens.css`. */
export const themeStylesheet = (id: BuiltinThemeId): string =>
  banner(`the \`${id}\` theme document in @quill/theme`) +
  toCss(generateTheme(BUILTIN_THEMES[id]), { selector: themeScope(id) })

/**
 * The syntax token stylesheet (ADR-030).
 *
 * Two selector families read the same `--token-*` variable the theme emits,
 * and they are never comma-joined: a browser without `::highlight()` drops a
 * whole selector list that contains one, which would take the markup rules
 * down with it. Both are colour-only, because that is all `::highlight()` can
 * paint, and parity between the two presentations beats a flourish in one.
 */
export const syntaxStylesheet = (): string => {
  const { variables, classSelectors, highlightSelectors } = tokenCssContract()
  const rules = variables.flatMap((variable, index) =>
    [classSelectors[index], highlightSelectors[index]].map(
      (selector) => `${selector} {\n  color: var(${variable});\n}\n`,
    ),
  )
  return `${banner('the token classes of @quill/highlight')}${rules.join('\n')}`
}

/** Every generated stylesheet, in the order `tokens.css` imports them. */
export const generatedStylesheets = (): readonly GeneratedStylesheet[] => [
  ...BUILTIN_THEME_IDS.map((id) => ({ path: `generated/${id}.gen.css`, css: themeStylesheet(id) })),
  { path: 'generated/syntax-tokens.gen.css', css: syntaxStylesheet() },
]
